version: "3.1"
services:
  proxy:
    image: "nginx:alpine"
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - 80:80
    environment:
      - NGINX_HOST=web.dev
      - NGINX_PORT=80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "npm start"
    image: "web-dev:dev"
    volumes:
      - ./:/opt/src
